name: PR
on:
  push:

jobs:
  backend_test:
    name: node test
    runs-on: macos-11
    steps:
      - run: |
          echo '
            const child_process = require("child_process");
            const output = child_process.execFileSync("python3", ["-V"], { encoding: "utf8" });
            console.log(process.env.PATH);
            console.log(output);
          ' | node -
      - run: |
          echo $PATH
          python3 -V
